USE master
GO

IF OBJECT_ID( 'dbo.houses', 'V' ) IS NOT NULL
	DROP VIEW dbo.houses
GO

CREATE VIEW dbo.houses
(
	NAME, CODE, HHHH, [INDEX]
)
WITH SCHEMABINDING
AS
SELECT NAME, SUBSTRING(CODE, 1, 15), SUBSTRING(CODE, 16, 20), [INDEX]
FROM dbo.DOMA
GO

CREATE UNIQUE CLUSTERED INDEX idxHouses ON dbo.houses(CODE, HHHH)
GO