USE [master]
GO

IF OBJECT_ID('separatedStreetCodes', 'V') IS NOT NULL
	DROP VIEW dbo.separatedStreetCodes
GO

CREATE VIEW dbo.separatedStreetCodes ( NAME, SS, RRR, GGG, PPP, YYYY, AA, SOCRNAME )
AS
SELECT DISTINCT 
	NAME, 
	SUBSTRING(CODE, 1, 2) AS SS, 
	SUBSTRING(CODE, 3, 3) AS RRR,
	SUBSTRING(CODE, 6, 3) AS GGG,
	SUBSTRING(CODE, 9, 3) AS PPP,
	SUBSTRING(CODE, 12, 4) AS SCODE,
	SUBSTRING(CODE, 16, 2) AS AA,
	lower(SOCRNAME)
FROM 
	dbo.STREET INNER JOIN dbo.SOCRBASE ON SCNAME = SOCR
	WHERE SUBSTRING(CODE, 16, 2) = '00'
GO

